# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=300, null=True)),
                ('CKey', models.IntegerField(blank=True)),
                ('Title', models.CharField(blank=True, max_length=300, null=True)),
                ('ImageURL', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
