# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=100, null=True)),
                ('Body', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
