# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=300, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('LinkURL', models.CharField(blank=True, max_length=300, null=True)),
                ('PhoneNo', models.CharField(blank=True, max_length=300, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('ParKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Facilities.Facility')),
            ],
        ),
    ]
